### ISSUE TITLE
TODO: Add Composer and the class to packagist.org

### ISSUE THREAD

**Issue by pH-7** [pH-7/QRCode-Generator-PHP-Class#3]
Like what I have already done for [PHP Cookie Session Manager](https://github.com/pH-7/CookieSession), 

- [x] Add composer.json file (like https://github.com/pH-7/CookieSession/blob/master/composer.json) 

- [x] Add the library to packagist.org (also like what has been done here https://packagist.org/packages/ph-7/cookiesession)

- [x] Update the README.md file and say it's now possible to install it through composer with `composer require ph-7/qrcode-generator` command.

**Comment by pH-7** [comment]
Done :smile:
